apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: product
  namespace: argocd
spec: 
  destination: 
    namespace: product
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: product
    repoURL: "https://github.com/selvaraj9k/Argocd.git"
    targetRevision: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
